// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syfkpifjsnsbdzculmos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5ZmtwaWZqc25zYmR6Y3VsbW9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTYyODQsImV4cCI6MjA2Mzc3MjI4NH0.pMe_zWOlu9WIveVVcEELcAXhlHAtXU4AQJwRsqHFAqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);